"""`keyhole init` — deterministic project/bootstrap initialization."""

from __future__ import annotations

import os
from pathlib import Path
from typing import List

from keyhole_cli.result import CommandResult, EXIT_SUCCESS, EXIT_FAILURE


_DEFAULT_COMPOSE = """\
# Keyhole public test runtime — generated by `keyhole init`
services:
  test-runtime:
    image: ghcr.io/keyhole-solution/test-runtime:latest
    ports:
      - "8080:8080"
"""

_DEFAULT_ENV = """\
# Keyhole runtime configuration
# KEYHOLE_RUNTIME_URL=
"""

_INIT_FILES = {
    "docker-compose.yml": _DEFAULT_COMPOSE,
    ".env": _DEFAULT_ENV,
}


def run_init(*, directory: str = ".") -> CommandResult:
    """Initialize a first-success workspace.

    Creates minimal local config files required for the public
    developer workflow.  Idempotent — existing files are skipped.
    """
    base = Path(directory).resolve()
    created: List[str] = []
    skipped: List[str] = []
    warnings: List[str] = []

    for filename, content in _INIT_FILES.items():
        target = base / filename
        if target.exists():
            skipped.append(filename)
        else:
            try:
                target.write_text(content, encoding="utf-8")
                created.append(filename)
            except OSError as exc:
                warnings.append(f"Could not create {filename}: {exc}")

    initialized = bool(created) or (not created and not warnings)
    success = not warnings

    next_steps = []
    if success:
        next_steps.append("Run 'keyhole runtime start' to start the local test runtime.")
    else:
        next_steps.append("Fix the warnings above and re-run 'keyhole init'.")

    return CommandResult(
        command="init",
        success=success,
        exit_code=EXIT_SUCCESS if success else EXIT_FAILURE,
        data={
            "initialized": initialized,
            "created_paths": created,
            "skipped_paths": skipped,
            "directory": str(base),
        },
        warnings=warnings,
        next_steps=next_steps,
        summary=(
            f"Initialized: created {len(created)} file(s), skipped {len(skipped)}"
            if success
            else "Initialization encountered errors"
        ),
    )
